### ISSUE TITLE
Seviyelerin isimlendirilmesi

### ISSUE THREAD

**Issue by kod7dev** [gelis-tr-io/website#6]
Seviyelerde **Software** kelimesinin yerine başka kelime kullanılabilir mi? Gelişmek kavramını destekleyecek ama daha genel bir şey.

**Comment by tarikguney** [comment]
Tavsiyelerin neler olabilir @kalecioyuncudev?

**Comment by tarikguney** [comment]
Bu konu hakkinda daha fazla yorum yok herhalde :) O zaman kapatiyorum. Yorum olunca yeniden acilabilir.
